<?php 
echo '<nav>
				<div class="navigation">
				<div class="nav-list" id="about-us"><a href="/Bazaar_Ceramics_ss/Homepage.php">Home Page</a></div>
				<div class="dropdown">
				<div class="nav-list"><a href="/Bazaar_Ceramics_ss/html/About_us.php">About us</a>
				<div class="dropdown-content">
					<a href="/Bazaar_Ceramics_ss/html/Company_history.php">Company Background</a>
					<a href="/Bazaar_Ceramics_ss/html/company_mission.php">Mission Statement</a>
					<a href="/Bazaar_Ceramics_ss/html/Production_process.php">Production and design process</a>
					<a href="/Bazaar_Ceramics_ss/html/Policies.php">Policies</a>
					<a href="/Bazaar_Ceramics_ss/html/Feedback.php">Feedback and contact</a>
					<a href="/Bazaar_Ceramics_ss/html/FAQ.php">FAQ</a>
				</div>
			</div></div>
			<div class="dropdown">
				<div class="nav-list"><a href="/Bazaar_Ceramics_ss/html/Display_catalogue.php">Display Catalogue</a>
				<div class="catalogue-dropdown-content">
					<a href="/Bazaar_Ceramics_ss/html/one-off_pieces.php">One-off Pieces</a>
					<a href="/Bazaar_Ceramics_ss/html/Homewares.php">Homewares</a>
				</div>
			</div></div>
				<div class="nav-list"><a href="/Bazaar_Ceramics_ss/html/Customer_registration.php">Customer Registration</a></div>
				<div class="dropdown">
					<div class="nav-list"><a href="/Bazaar_Ceramics_ss/html/Customer_login.php">Customer Login</a>
					<div class="catalogue-dropdown-content">
						<a href="/Bazaar_Ceramics_ss/html/Account_profile.php">Account Profile</a>
						<a href="/Bazaar_Ceramics_ss/html/Order_history.php">Order History</a>
					</div>
				</div></div>
				<div class="nav-list"><a class="active" href="/Bazaar_Ceramics_ss/html/members.php">Members Page</a></div>
		</div>
				</nav>'
?>